name: CCAuth
main: com.github.CubieX.CCAuth.CCAuth
author: CubieX
softdepend: [PermissionsEx, zPermissions, bPermissions, PermissionsBukkit]
version: 0.1.4
description: Validate player on server by forum account credentials on remote DB

commands:
    cca:
      aliases: [acc, account]
      description: Admin functions
      usage: /cca version | reload | help | verify <player>
    activate:
      description: Player functions
      usage: /activate <forum name> <forum pass>
    register:
      description: Player functions
      usage: /register <forum name> <forum pass> <forum pass> <eMail>

permissions:
    ccauth.use:
        description: Use normal commands
        default: op
    ccauth.admin:
        description: Allows use of all commands and effects
        default: op
        children:
          ccauth.use: true